### ISSUE TITLE
[Enhancement] Single BE / FE default table rep num

### ISSUE THREAD

**Issue by alanpaulkwan** [apache/doris#17423]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Description

If I don't have a three cluster deployment, I don't see why I should be required to type **"replication_allocation" = "tag.location.default: 1"** each time I want to create a table. It's cumbersome and I have to code around it. 

I also benefitted from talking directly to a member of the Doris team who so kindly reached out to me on Slack, but a beginner may not be able to understand the message **"
ERROR 1105 (HY000): Unexpected exception: errCode = 2, detailMessage = Failed to execute CTAS Reason: errCode = 2, detailMessage = Failed to find 3 backends for policy: cluster|query|load|schedule|tags|medium: default_cluster|false|false|true|[{"location" : "default"}]|HDD"** or at least the solution should be indicated.

### Solution

Can we create a global to remove it? 

Another solution (buit which then imposes straint on the team to design) would be to make it equivalent to the number of BE, and other replication counts are mandatory.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zy-kkk** [comment]
Hi, since Doris can only guarantee normal replica repair with 3 replication, we strongly recommend against changing the default number of table copies created. However, we are also concerned about the user experience with single BE testing, so we have two tasks here. The first is that we will optimize the error message. To make it easier to understand, the second is that the DDL provided in the Demo of our official website should BE 1 replication as far as possible. In the future, we may be improve the number of adaptive copies according to the number of BE; Finally, again, the production environment must guarantee 3 replication
