### ISSUE TITLE
[Bug] tablet xxx alive replica num 1 < quorum replica num 2

### ISSUE THREAD

**Issue by kiddlovemoon** [apache/doris#24993]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

2.0.1

### What's Wrong?

k8s集群部署doris-2.0.1，3 be、3 fe。
建表时表的配置为2副本，"replication_allocation" = "tag.location.default: 2"。
当模拟单个be故障时，插入数据与导入数据均报错tablet xxx alive replica num 1 < quorum replica num 2。
fe配置min_replication_num_per_tablet为1。

### What You Expected?

副本数为2，单个be故障应该可以继续写入。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by LemonLiTree** [comment]
As a distributed database, doris still needs to ensure the multi-copy principle, that is to say, most copies must be written successfully to be considered successful.So your best number of copies is an odd number.
The second parameter min_replication_num_per_tablet only sets the minimum number of replicas limit, rather than checking the minimum number of available replicas.
