### ISSUE TITLE
[Bug] sql-convertor hive to doris synax wrong

### ISSUE THREAD

**Issue by roamerop** [apache/doris#41182]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/doris/issues?q=is%3Aissue) and found no similar issues.

### Version

3.0.1

### What's Wrong?

hive sql to doris sql synax wrong

### What You Expected?

hive sql to doris sql synax wrong

### How to Reproduce?

online address： https://play.selectdb.com/sql-convertor?case_sensitive=0&from=hive
- hive sql
```select (cast('2000-08-19' as date) + 14 days) from table_name```

- doris sql
```
SELECT
  (
    CAST('2000-08-19' AS DATE) + 14 AS days
  )
FROM table_name AS table_name
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by liujiwen-up** [comment]
This syntax is not standard Hive syntax. Currently, this non-standard writing method will conflict with normal digital addition and subtraction.
The standard syntax in Hive is 
`select (cast('2000-08-19' as date) + interval 14 days) from table_name.` 
This Hive SQL can be accurately converted
`SELECT CAST('2000-08-19' AS DATE) + INTERVAL '14' DAY from table_name` 
SQL-Converter will automatically change the unit from `days` to` day` so that it can be executed correctly in doris
