### ISSUE TITLE
Rollup SQL in TPCDS encounter the wrong answer.

### ISSUE THREAD

**Issue by chaoyli** [apache/doris#4427]
```
select 'catalog channel' as channel
       , cs_call_center_sk as id
       , sum(cs_ext_sales_price)
from  catalog_sales
where cs_sold_date_sk = 2451780
group by rollup (channel, id)
order by channel,id
```

**Comment by yangzhg** [comment]
This is because the completion of the constant column in our implementation is in aggNode. The calculation of rollup repetition is done between scanNode and agg, so the constant cannot be repeated correctly. This problem is difficult to solve under our current framework. I think Refactor the implementation of grouping set to solve this problem
